/* The Pythagorean theorem states that the sum of the squares of the sides of a right triangle is equal to the
 * square of the hypotenuse. For example, if two sides of a right triangle have lenghs of 3 and 4, then the 
 * hypotenuse must have a lenght of 5. Together the integers 3, 4, and 5 form a Pythagorean triple. There are an 
 * infinite number of such triples. Given two positive integers, m and n, where m > n, a Pthagorean triple can be
 * generated by the following formulas: 
 * side1 = m ** 2 - n ** 2
 * side2 = 2mn
 * hypotenuse = m ** 2 + n**2
 * The triple (side1 = 3, side2 = 4, hypotenuse = 5) is generated by this formula when m = 2 and n = 1. Write a 
 * program that takes values for m and n as input and displays the values of the Pythagorean triple generated 
 * by the formulas above.
 *
 * Author: C. Maxwell Reilly
 * Date: Friday February 24, 2023
 */

#include <stdio.h>

int main (void) {
    int m, n;
    int side1, side2, hypotenuse;
    printf("Enter two numbers to generate a Pythagorean triple. Make sure that the first number is larger than the second number.\nNumber One >> ");
    scanf("%d", &m);
    printf("\n Number Two >> ");
    scanf("%d", &n);
    side1 = (m * m) - (n * n);
    side2 = 2 * m * n;
    hypotenuse = (m * m) + (n * n);
    printf("\nSide one: %d\nSide two: %d\n Hypotenuse: %d\n", side1, side2, hypotenuse);
    return (0);
}
